version: '3'

services:
  mysql:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jnation-demo
    ports:
      - "3307:3306"

volumes:
  container-volume:
